import { BookOpen } from 'lucide-react';

const SECTIONS = [
  { icon: '💼', title: 'Account & Portfolio',  color: '#00e676', text: 'Every signed-in user starts with $10,000 USDC in Firebase-backed paper funds. You can reset your portfolio anytime from the Portfolio page. No real money is ever used.' },
  { icon: '🤖', title: 'AI Agent',             color: '#f97316', text: 'Signals are generated by Gemini 2.5 Flash (Deep Reasoning) and Groq LLaMA 3.3 70B (Fast Output) using live Binance price data. Always review the full reasoning before acting. AI signals are not financial advice.' },
  { icon: '⚠️', title: 'Risk Warning',          color: '#f43f5e', text: 'Cryptocurrency markets are highly volatile and unpredictable. Past performance does not guarantee future results. Never invest more than you can afford to lose. SoSo SMRE is for educational and research purposes only.' },
  { icon: '⭐', title: 'SoPoints Rewards',      color: '#f59e0b', text: 'Earn 1 SoPoint for every $100 of paper-trading volume. SoPoints will be redeemable through the SoDEX integration. The more you research and practice, the more SoPoints you accumulate.' },
  { icon: '🔒', title: 'Data & Privacy',        color: '#3b82f6', text: 'Portfolio and trade data is stored per user in Firebase Firestore. Market data is sourced from Binance public APIs and SoSoValue / Reddit feeds.' },
  { icon: '⚡', title: 'SoDEX Integration',     color: '#a855f7', text: 'SoDEX (Mainnet: mainnet-gw.sodex.dev) is a decentralised exchange. API keys require Closed Alpha access at sodex.com/apikeys. Write endpoints use EIP-712 signatures. Public market data requires no authentication.' },
];

export default function GuidelinesPage() {
  return (
    <div style={{ padding: 24, maxWidth: 760 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
        <BookOpen size={20} color="#f97316" />
        <h1 style={{ fontSize: 22, fontWeight: 700, color: '#fff' }}>Guidelines</h1>
      </div>
      <p style={{ fontSize: 13, color: '#444', marginBottom: 24 }}>SoSo SMRE — Smart Money Research Engine — Platform Rules</p>

      <div style={{ background: 'linear-gradient(135deg,#12103a,#0e1a4a,#0b1535)', border: '1px solid #2a2060', borderRadius: 16, padding: '20px 24px', marginBottom: 24 }}>
        <p style={{ fontSize: 14, fontWeight: 600, color: '#c0c0ff', lineHeight: 1.65 }}>
          Welcome to <span style={{ color: '#f97316', fontWeight: 800 }}>SoSo SMRE</span> — the Smart Money Research Engine. This platform provides AI-powered crypto trading intelligence, live market data powered by Binance and SoSoValue APIs, and paper trading capabilities to help you develop strategies in a risk-free environment.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {SECTIONS.map(s => (
          <div key={s.title} style={{ background: '#111', border: '1px solid #1e1e1e', borderRadius: 14, padding: '18px 20px', borderLeft: `3px solid ${s.color}` }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
              <span style={{ fontSize: 20 }}>{s.icon}</span>
              <h3 style={{ fontSize: 14, fontWeight: 700, color: s.color }}>{s.title}</h3>
            </div>
            <p style={{ fontSize: 13, color: '#777', lineHeight: 1.65, paddingLeft: 30 }}>{s.text}</p>
          </div>
        ))}
      </div>

      <div style={{ marginTop: 24, padding: '14px 20px', background: '#111', border: '1px solid #1e1e1e', borderRadius: 12, fontSize: 11, color: '#444', textAlign: 'center', lineHeight: 1.7 }}>
        SoSo SMRE v1.0 · Built with Next.js 15 + Gemini 2.5 Flash + Groq LLaMA 3.3 · Market data from Binance · News from SoSoValue API · Not financial advice · Educational use only
      </div>
    </div>
  );
}
